In [1]:
import pandas as pd
import numpy as np

In [2]:
values = pd.Series(['apple', 'orange', 'apple', 'apple']*2)

In [3]:
values

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
dtype: object

In [4]:
values.unique()

array(['apple', 'orange'], dtype=object)

In [5]:
values.value_counts()

apple     6
orange    2
dtype: int64

In [15]:
pd.unique(values)

array([0, 1], dtype=int64)

In [16]:
values = pd.Series([0,1,0,0]*2)

In [17]:
dim = pd.Series(['apple', 'orange'])

In [18]:
values

0    0
1    1
2    0
3    0
4    0
5    1
6    0
7    0
dtype: int64

In [19]:
dim

0     apple
1    orange
dtype: object

In [20]:
dim.take(values)

0     apple
1    orange
0     apple
0     apple
0     apple
1    orange
0     apple
0     apple
dtype: object

In [22]:
fruits = ['apple', 'orange', 'apple', 'apple'] * 2

In [24]:
fruits

['apple', 'orange', 'apple', 'apple', 'apple', 'orange', 'apple', 'apple']

In [25]:
N = len(fruits)

In [26]:
N

8

In [27]:
df = pd.DataFrame({
    'fruit': fruits, 
    'basket_id': np.arange(N),
    'count': np.random.randint(3,15,size=N),
    'weight': np.random.uniform(0,4,size=N)
    },
    columns = ['basket_id', 'fruit', 'count', 'weight']
)

In [28]:
df

basket_id   fruit  count    weight
0          0   apple      5  0.566058
1          1  orange     13  2.891277
2          2   apple     11  0.113092
3          3   apple      8  1.151449
4          4   apple     11  0.180559
5          5  orange     13  2.499788
6          6   apple     10  3.137494
7          7   apple      8  1.977918

In [34]:
fruit_cat = df['fruit'].astype('category')

In [35]:
fruit_cat

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
Name: fruit, dtype: category
Categories (2, object): ['apple', 'orange']

In [36]:
c = fruit_cat.values

In [37]:
c

['apple', 'orange', 'apple', 'apple', 'apple', 'orange', 'apple', 'apple']
Categories (2, object): ['apple', 'orange']

In [38]:
type(c)

pandas.core.arrays.categorical.Categorical

In [39]:
c.codes

array([0, 1, 0, 0, 0, 1, 0, 0], dtype=int8)

In [41]:
c.categories

Index(['apple', 'orange'], dtype='object')

In [42]:
c.codes

array([0, 1, 0, 0, 0, 1, 0, 0], dtype=int8)

In [43]:
df

basket_id   fruit  count    weight
0          0   apple      5  0.566058
1          1  orange     13  2.891277
2          2   apple     11  0.113092
3          3   apple      8  1.151449
4          4   apple     11  0.180559
5          5  orange     13  2.499788
6          6   apple     10  3.137494
7          7   apple      8  1.977918

In [44]:
df['fruit'] = df['fruit'].astype('category')

In [45]:
df['fruit']

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
Name: fruit, dtype: category
Categories (2, object): ['apple', 'orange']

In [46]:
my_categories = pd.Categorical(['foo', 'bar', 'baz', 'foo', 'bar'])

In [47]:
my_categories

['foo', 'bar', 'baz', 'foo', 'bar']
Categories (3, object): ['bar', 'baz', 'foo']

In [48]:
my_categories.categories

Index(['bar', 'baz', 'foo'], dtype='object')

In [49]:
my_categories.codes

array([2, 0, 1, 2, 0], dtype=int8)

In [56]:
categories = ['foo', 'bar', 'baz']

In [57]:
codes = [0,1,2,0,0,1]

In [58]:
my_cats_2 = pd.Categorical.from_codes(codes, categories)

In [59]:
my_cats_2

['foo', 'bar', 'baz', 'foo', 'foo', 'bar']
Categories (3, object): ['foo', 'bar', 'baz']

In [60]:
ordered_cat = pd.Categorical.from_codes(codes, categories, ordered=True)

In [61]:
ordered_cat

['foo', 'bar', 'baz', 'foo', 'foo', 'bar']
Categories (3, object): ['foo' < 'bar' < 'baz']

In [62]:
my_cats_2.as_ordered()

['foo', 'bar', 'baz', 'foo', 'foo', 'bar']
Categories (3, object): ['foo' < 'bar' < 'baz']

In [63]:
my_cats_2.as_ordered().as_unordered()

['foo', 'bar', 'baz', 'foo', 'foo', 'bar']
Categories (3, object): ['foo', 'bar', 'baz']

In [64]:
np.random.seed(12345)

In [78]:
draws = np.random.randn(1000)

In [79]:
draws[:5]

array([-0.98350472,  0.93094376, -0.81167564, -1.83015626, -0.13873015])

In [80]:
bins = pd.qcut(draws, 4)

In [81]:
bins

[(-3.746, -0.623], (0.677, 3.26], (-3.746, -0.623], (-3.746, -0.623], (-0.623, -0.0206], ..., (-3.746, -0.623], (-0.623, -0.0206], (-0.623, -0.0206], (-3.746, -0.623], (0.677, 3.26]]
Length: 1000
Categories (4, interval[float64]): [(-3.746, -0.623] < (-0.623, -0.0206] < (-0.0206, 0.677] < (0.677, 3.26]]

In [82]:
bins = pd.qcut(draws, 4, labels=['Q1', 'Q2', 'Q3', 'Q4'])

In [83]:
bins

['Q1', 'Q4', 'Q1', 'Q1', 'Q2', ..., 'Q1', 'Q2', 'Q2', 'Q1', 'Q4']
Length: 1000
Categories (4, object): ['Q1' < 'Q2' < 'Q3' < 'Q4']

In [84]:
bins.codes[:10]

array([0, 3, 0, 0, 1, 2, 2, 1, 3, 2], dtype=int8)

In [85]:
bins = pd.Series(bins, name = 'quartile')

In [86]:
bins

0      Q1
1      Q4
2      Q1
3      Q1
4      Q2
       ..
995    Q1
996    Q2
997    Q2
998    Q1
999    Q4
Name: quartile, Length: 1000, dtype: category
Categories (4, object): ['Q1' < 'Q2' < 'Q3' < 'Q4']

In [87]:
results = (pd.Series(draws).groupby(bins)
          .agg(['count', 'min', 'max'])
          .reset_index())

In [88]:
results

quartile  count       min       max
0       Q1    250 -3.745356 -0.627426
1       Q2    250 -0.621249 -0.021299
2       Q3    250 -0.019941  0.677246
3       Q4    250  0.677263  3.260383

In [89]:
results['quartile']

0    Q1
1    Q2
2    Q3
3    Q4
Name: quartile, dtype: category
Categories (4, object): ['Q1' < 'Q2' < 'Q3' < 'Q4']

In [91]:
N  = 10000000

In [92]:
draws = pd.Series(np.random.randn(N))

In [93]:
labels = pd.Series(['foo', 'bar', 'baz', 'qux'] * (N//4))

In [94]:
categories = labels.astype('category')

In [95]:
labels.memory_usage()

80000128

In [96]:
categories.memory_usage()

10000320

In [97]:
s  = pd.Series(['a', 'b', 'c', 'd'] * 2)

In [98]:
s

0    a
1    b
2    c
3    d
4    a
5    b
6    c
7    d
dtype: object

In [99]:
cat_s = s.astype('category')

In [100]:
cat_s

0    a
1    b
2    c
3    d
4    a
5    b
6    c
7    d
dtype: category
Categories (4, object): ['a', 'b', 'c', 'd']

In [103]:
cat_s.cat.codes

0    0
1    1
2    2
3    3
4    0
5    1
6    2
7    3
dtype: int8

In [104]:
cat_s.cat.categories

Index(['a', 'b', 'c', 'd'], dtype='object')

In [105]:
actual_categories = ['a', 'b', 'c', 'd','e']

In [106]:
cat_s2 = cat_s.cat.set_categories(actual_categories)

In [107]:
cat_s2

0    a
1    b
2    c
3    d
4    a
5    b
6    c
7    d
dtype: category
Categories (5, object): ['a', 'b', 'c', 'd', 'e']

In [108]:
cat_s.value_counts()

d    2
c    2
b    2
a    2
dtype: int64

In [109]:
cat_s2.value_counts()

d    2
c    2
b    2
a    2
e    0
dtype: int64

In [110]:
cat_s3 = cat_s[cat_s.isin(['a','b'])]

In [111]:
cat_s3

0    a
1    b
4    a
5    b
dtype: category
Categories (4, object): ['a', 'b', 'c', 'd']

In [112]:
cat_s3.cat.remove_unused_categories()

0    a
1    b
4    a
5    b
dtype: category
Categories (2, object): ['a', 'b']

In [113]:
cat_s

0    a
1    b
2    c
3    d
4    a
5    b
6    c
7    d
dtype: category
Categories (4, object): ['a', 'b', 'c', 'd']

In [114]:
cat_s = pd.Series(['a', 'b', 'c', 'd'] * 2, dtype = 'category')

In [115]:
pd.get_dummies(cat_s)

a  b  c  d
0  1  0  0  0
1  0  1  0  0
2  0  0  1  0
3  0  0  0  1
4  1  0  0  0
5  0  1  0  0
6  0  0  1  0
7  0  0  0  1

In [116]:
df = pd.DataFrame(
    {
        'key': ['a', 'b', 'c'] * 4, 
        'value': np.arange(12.)
    }
)

In [117]:
df

key  value
0    a    0.0
1    b    1.0
2    c    2.0
3    a    3.0
4    b    4.0
5    c    5.0
6    a    6.0
7    b    7.0
8    c    8.0
9    a    9.0
10   b   10.0
11   c   11.0

In [118]:
g = df.groupby('key').value

In [120]:
g.mean()

key
a    4.5
b    5.5
c    6.5
Name: value, dtype: float64

In [123]:
g.transform(lambda x: x.mean())

0     4.5
1     5.5
2     6.5
3     4.5
4     5.5
5     6.5
6     4.5
7     5.5
8     6.5
9     4.5
10    5.5
11    6.5
Name: value, dtype: float64

In [124]:
g.transform('mean')

0     4.5
1     5.5
2     6.5
3     4.5
4     5.5
5     6.5
6     4.5
7     5.5
8     6.5
9     4.5
10    5.5
11    6.5
Name: value, dtype: float64

In [126]:
list(g)

[('a', 0    0.0
  3    3.0
  6    6.0
  9    9.0
  Name: value, dtype: float64), ('b', 1      1.0
  4      4.0
  7      7.0
  10    10.0
  Name: value, dtype: float64), ('c', 2      2.0
  5      5.0
  8      8.0
  11    11.0
  Name: value, dtype: float64)]

In [127]:
g.transform(lambda x: x**2)

0       0.0
1       1.0
2       4.0
3       9.0
4      16.0
5      25.0
6      36.0
7      49.0
8      64.0
9      81.0
10    100.0
11    121.0
Name: value, dtype: float64

In [128]:
g.transform(lambda x:x.rank(ascending = False))

0     4.0
1     4.0
2     4.0
3     3.0
4     3.0
5     3.0
6     2.0
7     2.0
8     2.0
9     1.0
10    1.0
11    1.0
Name: value, dtype: float64

In [129]:
def normalize(x):
    return (x-x.mean())/x.std()

In [130]:
g.transform(normalize)

0    -1.161895
1    -1.161895
2    -1.161895
3    -0.387298
4    -0.387298
5    -0.387298
6     0.387298
7     0.387298
8     0.387298
9     1.161895
10    1.161895
11    1.161895
Name: value, dtype: float64

In [131]:
g.apply(normalize)

0    -1.161895
1    -1.161895
2    -1.161895
3    -0.387298
4    -0.387298
5    -0.387298
6     0.387298
7     0.387298
8     0.387298
9     1.161895
10    1.161895
11    1.161895
Name: value, dtype: float64